### ISSUE TITLE
Is it supposed to update this often?

### ISSUE THREAD

**Issue by jbryson3** [glimmerjs/glimmer-demos#3]
![apr-07-2017 13-51-05](https://cloud.githubusercontent.com/assets/675098/24812747/5ecdcfd4-1b99-11e7-839d-da921664634b.gif)

If so, it's an impressive update rate, however it suffers a bit UX wise.

**Comment by rwjblue** [comment]
The demo is supposed to show possible rerender speed, not an accurate GH timeline 😝

**Comment by jbryson3** [comment]
Well then it achieves its intended effect! Thanks
